apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    run: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"     
    app: "{{ .Release.Name }}"
  namespace: default
  #resourceVersion: "100"
  #selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/example
  #uid: fd03ac95-a84b-11e7-a417-0800277e13b3
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      #creationTimestamp: null
      labels:
        app: "{{ .Release.Name }}"
        run: "{{ .Release.Name }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  #selector:
  #  matchLabels:
  #    run: "{{ .Release.Name }}"
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 1
  #    maxUnavailable: 1
    type: RollingUpdate
    spec:
      #{{- if .Values.nginxcache.pullSecret }}    
      #      imagePullSecrets:
      #        - name: "{{ .Values.nginxcache.pullSecret }}"
      #{{- end }}          
      containers:
      - name: {{ .Values.nginxcache.name }}
        image: {{ .Values.nginxcache.registry }}/{{ .Values.nginxcache.repository }}:{{ .Values.nginxcache.tag }}
        imagePullPolicy: {{ .Values.nginxcache.pullPolicy }}
        resources: {}
        #terminationMessagePath: /dev/termination-log
        #terminationMessagePolicy: File
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 1935

        #dnsPolicy: ClusterFirst
        #restartPolicy: Always
        #schedulerName: default-scheduler
        #securityContext: {}
        #terminationGracePeriodSeconds: 30

        volumeMounts:
        - mountPath: /smileserv/vhosts
          name: sl-cache-vhosts
        - mountPath: /var/log/nginx
          name: logs
        - mountPath: /sl-cache
          name: sl-cache
   
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo nameserver 10.96.0.10 > /etc/resolv.conf && echo search default.svc.cluster.local svc.cluster.local cluster.local >> /etc/resolv.conf && echo options ndots:2 >> /etc/resolv.conf"]
              #command: ["/bin/sh", "-c", "echo nameserver 10.96.0.10 > /etc/resolv.conf && echo search default.svc.cluster.local svc.cluster.local cluster.local >> /etc/resolv.conf && echo options ndots:2 >> /etc/resolv.conf && rm -rf /smileserv/scripts && /usr/bin/git clone https://github.com/smileserv/scripts /smileserv/scripts && chmod -R 700 /smileserv/scripts && sh /smileserv/scripts/init_cache.sh"]
          #preStop:
          #  exec:
          #    command: ["exit"]
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

      volumes:
      - name: sl-cache-vhosts
        configMap:
          name: sl-cache-vhosts
          #items:
          #  - key: source.conf
          #    path: source.conf

      - name: sl-cache
        emptyDir:
          medium: Memory
          sizeLimit: "10Gi"

      - name: logs
        emptyDir: {}
