apiVersion: v1
kind: ConfigMap
metadata:
  name: vhosts
  labels:
    app: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "vhosts/*.conf").AsConfig | indent 2 }}
